name: shellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: make shellcheck
